#!/bin/bash
set -e

ARG=$1

# See https://stackoverflow.com/a/246128/2570880
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


function install {
    FILE=$1
    TARGET=$2
    TARGET_DIR=$(dirname $TARGET)

    if [ -e $TARGET_DIR ]; then
        if [ ! -d $TARGET_DIR ]; then
            echo "$TARGET_DIR is not a directory"
            exit 1
        fi
    else
        mkdir -p $TARGET_DIR
    fi

    if [ -e $TARGET -a ! -L $TARGET -a "$ARG" != "-f" ]; then
        echo "$TARGET exists and is not a symlink; use ./install -f to force."
    else
        ln -sf $DIR/$FILE $TARGET_DIR
        echo "$1 => $2"
    fi
}

if [ "$OS" == "Windows_NT" ]; then
    NVIM_CONFIG="~/AppData/Local/nvim"
else
    NVIM_CONFIG="~/.config/nvim"
fi

install bash_profile ~/.bash_profile
install bashrc       ~/.bashrc
install gitconfig    ~/.gitconfig
install init.vim     $NVIM_CONFIG/init.vim
install clojure.vim  $NVIM_CONFIG/clojure.vim
install notes.vim    $NVIM_CONFIG/notes.vim
install UltiSnips    $NVIM_CONFIG/UltiSnips
install a2psrc       ~/.a2ps/a2psrc
